### ISSUE TITLE
What's the problem? 

### ISSUE THREAD

**Issue by sablesoft** [astorm/MagentoBetter404#6]
I'm new to Magento. I did all of the instructions, but page 404 remains. Maybe it's in some magento settings? Your debbager a very useful thing, but now it shows that everything is in order.

Can you please tell, why is not there a white screen and the inscription "Hello World"?

404 Screenshot:
http://take.ms/M5lpm

Files:
/app/etc/modules/SableCom_FirstMod.xml

``` xml
<?xml version="1.0"?>
<config>
    <modules>
        <SableCom_FirstMod>
            <active>true</active>
            <codePool>local</codePool>
        </SableCom_FirstMod>
    </modules>
</config>
```

/app/code/local/SableCom/FirstMod/etc/config.xml

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<config>
    <modules>
        <SableCom_FirstMod>
            <version>0.1.0</version>
        </SableCom_FirstMod>
    </modules>
    <frontend>
        <routers>
            <firstmod>
                <use>standart</use>
                <args>
                    <module>SableCom_FirstMod</module>
                    <frontName>firstmod</frontName>
                </args>
            </firstmod>
        </routers>
    </frontend>
</config>
```

/app/code/local/SableCom/FirstMod/controllers/IndexController.php

``` php
<?php 
    class SableCom_FirstMod_IndexController extends Mage_Core_Controller_Front_Action {
        public function indexAction() {
            echo 'Hello World!';
        }
    }
?>
```

**Comment by sablesoft** [comment]
I found my mistake. I'm sorry, I was wrong by one letter.
I wrote

``` xml
<use>standart</use>
```

But correct record

``` xml
<use>standard</use>
```

I'm ashamed) But happy that the error was found.

**Comment by astorm** [comment]
@itBrujo No need to feel ashamed -- there's way to much  information to keep track of in your head during a Magento project:)  

Marking this as dupe of: https://github.com/astorm/MagentoBetter404/issues/3
